#!/bin/bash
set -e

echo "Starting postBuild script..."

# Ensure the .jupyter directory exists
#mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension


#mkdir -p /home/jovyan/src/
mkdir -p $HOME/.jupyter/

mkdir -p /jovyan/local/etc/jupyter/lab/ # system wide configuration
mkdir -p ~/.jupyter/lab/workspaces/ # workspaces
mkdir -p ~/.jupyter/lab/settings/
mkdir -p /jovyan/local/etc/jupyter/lab/settings/


#if [ $? -eq 0 ]; then
#    echo "Created .jupyter directory successfully."
#else
#    echo "Failed to create .jupyter directory."
#fi



# Copy the overrides.json file to the appropriate directory
#cp .binder/overrides.json ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension/overrides.json

cp .binder/overrides.json /home/jovyan/src/
cp .binder/overrides.json $HOME/.jupyter/

cp $HOME/.binder/overrides.json /jovyan/local/etc/jupyter/lab/ # system wide configuration
cp $HOME/.binder/overrides.json ~/.jupyter/lab/workspaces/ # workspaces
cp $HOME/.binder/overrides.json ~/.jupyter/lab/settings/
cp $HOME/.binder/overrides.json /jovyan/local/etc/jupyter/lab/settings



#if [ $? -eq 0 ]; then
#    echo "Copied overrides.json successfully."
#else
   # echo "Failed to copy overrides.json."
#fi

# Final echo to indicate completion
echo "postBuild script completed."
