#!/bin/bash
set -e

echo "Starting postBuild script..."

# Ensure the .jupyter directory exists
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension

# Copy the overrides.json file to the appropriate directory
cp .binder/overrides.json ~/.jupyter/lab/user-settings/@jupyterlab/shortcuts-extension/overrides.json


#/home/jovyan/.jupyter/jupyter_ai/config.json

echo "postBuild script completed."
