#!/bin/bash
jupyter lab --AiExtension.default_language_model=openai-chat:gpt-4


#!/usr/bin/env bash
#set -eux

# Create the directory
#mkdir -p ${HOME}/.local/share/jupyter/jupyter_ai
#mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings

# Copy the overrides.json file
#cp binder/config.json ${HOME}/.local/share/jupyter/jupyter_ai
#cp overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
